export const FETCH_APPLICATIONCOMPANY_REQUEST = 'FETCH_APPLICATIONCOMPANY_REQUEST'
export const FETCH_APPLICATIONCOMPANY_SUCCESS = 'FETCH_APPLICATIONCOMPANY_SUCCESS'
export const FETCH_APPLICATIONCOMPANY_FAILURE = 'FETCH_APPLICATIONCOMPANY_FAILURE'
export const ROLEAPP_ADDED = 'ROLEAPP_ADDED'