export const FETCH_COMPANYCORRES_REQUEST = 'FETCH_COMPANYCORRES_REQUEST'
export const FETCH_COMPANYCORRES_SUCCESS = 'FETCH_COMPANYCORRES_SUCCESS'
export const FETCH_COMPANYCORRES_FAILURE = 'FETCH_COMPANYCORRES_FAILURE'
