export const FETCH_EMPLOYEECOMPANY_REQUEST = 'FETCH_EMPLOYEECOMPANY_REQUEST'
export const FETCH_EMPLOYEECOMPANY_SUCCESS = 'FETCH_EMPLOYEECOMPANY_SUCCESS'
export const FETCH_EMPLOYEECOMPANY_FAILURE = 'FETCH_EMPLOYEECOMPANY_FAILURE'
