export const FETCH_FEATURE_REQUEST = 'FETCH__REQUEST'
export const FETCH_FEATURE_SUCCESS = 'FETCH_FEATURE_SUCCESS'
export const FETCH_FEATURE_FAILURE = 'FETCH_FEATURE_FAILURE'
   
export const ADD_FEATURE = 'ADD_FEATURE'
export const UPDATE_FEATURE = 'UPDATE_FEATURE'      
export const DELETE_FEATURE = 'DELETE_FEATURE'
export const SEARCH_FEATURE = 'SEARCH_FEATURE'