export const FETCH_MENUFEATURE_REQUEST = 'FETCH__REQUEST'
export const FETCH_MENUFEATURE_SUCCESS = 'FETCH_MENUFEATURE_SUCCESS'
export const FETCH_MENUFEATURE_FAILURE = 'FETCH_MENUFEATURE_FAILURE'
   
export const ADD_MENUFEATURE = 'ADD_MENUFEATURE'
export const UPDATE_MENUFEATURE = 'UPDATE_MENUFEATURE'      
export const DELETE_MENUFEATURE = 'DELETE_MENUFEATURE'
export const SEARCH_MENUFEATURE = 'SEARCH_MENUFEATURE'