export const FETCH_MENUITEMFEATURE_REQUEST = 'FETCH__REQUEST'
export const FETCH_MENUITEMFEATURE_SUCCESS = 'FETCH_MENUITEMFEATURE_SUCCESS'
export const FETCH_MENUITEMFEATURE_FAILURE = 'FETCH_MENUITEMFEATURE_FAILURE'
   
export const ADD_MENUITEMFEATURE = 'ADD_MENUITEMFEATURE'
export const UPDATE_MENUITEMFEATURE = 'UPDATE_MENUITEMFEATURE'      
export const DELETE_MENUITEMFEATURE = 'DELETE_MENUITEMFEATURE'
export const SEARCH_MENUITEMFEATURE = 'SEARCH_MENUITEMFEATURE'