export const FETCH_ACCESS_FEATURE_REQUEST = 'FETCH_ACCESS_FEATURE_REQUEST'
export const FETCH_ACCESS_FEATURE_SUCCESS = 'FETCH_ACCESS_FEATURE_SUCCESS'
export const FETCH_ACCESS_FEATURE_FAILURE = 'FETCH_ACCESS_FEATURE_FAILURE'